### ISSUE TITLE
crash on join local server (1.18.2) java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists

### ISSUE THREAD

**Issue by SDUBZ** [grim3212/AssortedWorld#1]
AW: assortedworld-1.18.2-3.0.0.jar
forge: 1.18.2- 40.1.0
crash
[crash-2022-04-30_22.48.36-server.txt](https://github.com/grim3212/AssortedWorld/files/8596921/crash-2022-04-30_22.48.36-server.txt)

logs:
[debug.log](https://github.com/grim3212/AssortedWorld/files/8596922/debug.log)
[latest.log](https://github.com/grim3212/AssortedWorld/files/8596923/latest.log)

**Comment by grim3212** [comment]
Looks like I accidentally used the wrong list class. I didn't catch in dev since it only would crash when everything is actually built out.

Thanks for the report!

It has been fixed with [assortedworld-1.18.2-3.0.1.jar](https://www.curseforge.com/minecraft/mc-mods/assorted-world/files/3773976)
