### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Rogenar** [grim3212/AssortedWorld#2]
[latest.log](https://github.com/grim3212/AssortedWorld/files/11272293/latest.log)
[rei.log](https://github.com/grim3212/AssortedWorld/files/11272294/rei.log)
[crash-2023-04-19_14.05.52-client.txt](https://github.com/grim3212/AssortedWorld/files/11272296/crash-2023-04-19_14.05.52-client.txt)
[rei-issues.log](https://github.com/grim3212/AssortedWorld/files/11272297/rei-issues.log)

**Comment by grim3212** [comment]
Thanks for the bug report!

It doesn't actually look like an issue but an issue with Assorted Storage and Assorted Tech.
I was unable to repro but I think I added a fix for each of those that hopefully will fix the crash.

Please try out the latest versions of both of those and if they still crash please open a bug report on one of those.

**Comment by Rogenar** [comment]
problem fixed. Mods work fine.

**Comment by grim3212** [comment]
Great thanks for confirming!
